AllCops:

 TargetRubyVersion: 2.4
 TargetRailsVersion: 5.1

 Exclude:
   - '**/templates/**/*'
   - '**/vendor/**/*'
   - 'Gemfile'
   - 'Guardfile'
   - 'tmp/**/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'spec/*_helper.rb'
   - 'lib/tasks/**/*'
   - 'try/**/*'

 DisplayCopNames: yes
 DisplayStyleGuide: yes
 ExtraDetails: yes

Rails:
 Enabled: yes

Style/TernaryParentheses:
 Enabled: no

Style/FrozenStringLiteralComment:
 Enabled: no

Style/MutableConstant:
 Enabled: no

Style/Not:
 Enabled: no

Style/StringLiterals:
 Enabled: no

Style/Documentation:
 Enabled: no

Style/SignalException:
 Enabled: no

Style/For:
 Enabled: no

Style/AndOr:
 Enabled: no

Style/FormatString:
 EnforcedStyle: percent

Style/TrailingCommaInArguments:
 Enabled: no

Style/TrailingCommaInLiteral:
 Enabled: no

Style/EmptyMethod:
 Enabled: no

Style/SymbolArray:
 Enabled: no

Style/PercentLiteralDelimiters:
 Enabled: no

Style/LambdaCall:
 Enabled: no

Layout/SpaceBeforeBlockBraces:
 Enabled: no

Layout/EmptyLinesAroundClassBody:
 Enabled: no

Layout/EmptyLinesAroundModuleBody:
 Enabled: no

Layout/EmptyLinesAroundBlockBody:
 Enabled: no

Layout/AlignHash:
 EnforcedLastArgumentHashStyle: ignore_implicit

Layout/CaseIndentation:
 IndentOneStep: true

Metrics/LineLength:
 Max: 120

Metrics/MethodLength:
 Max: 20

Metrics/AbcSize:
 Max: 30

Metrics/ModuleLength:
 Max: 150

Rails/HasAndBelongsToMany:
 Enabled: no

